[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  # Optional: if you have a build process for frontend assets, configure here
  # command = "npm run build"
  # publish = "public"

[dev]
  command = "npm run dev" # Or yarn dev if you use yarn
  functions = "netlify/functions"
  port = 8888 